Jenkins fails, Neutron stable/mitaka branch gone
tox pep8 is failing because stable/mitaka no longer exists for neutron.
Need to update tox.ini. Error seen is as follows:
~/nwcisco-dblock2/.tox/pep8/src/neutron$ git checkout -q stable/mitaka
error: pathspec 'stable/mitaka' did not match any file(s) known to git

Change-Id: I5d6fc9b57c355fa1d6c3f0bc9a3c0c8b388aba68
Closes-bug:  #1702670